--- IMPORT THE DATASET FROM EXCEL --- 
SELECT * FROM [GRADERECORD] 
--- DELETE DUPLICATES --- 
WITH list_rownumbers AS
(
SELECT studentID, First_name, 
ROW_NUMBER() OVER (ORDER BY studentID, First_name) AS 'RowNumber' 
FROM [GRADERECORD] 
) 
DELETE list_rownumbers WHERE RowNumber not in 
( SELECT min(RowNumber) FROM list_rownumbers GROUP BY studentID, First_name) 

-- CORRECTED A COLUMN TO HELP MAKE IT CONSISTANT --- 
EXEC SP_RENAME 'GRADERECORD.First_name', 'Firstname', 'Column';
--- GETTING SECOND FORM NORMALIZATION TABLES ---
SELECT studentID, Firstname, Lastname
INTO SECONDFORM
FROM GRADERECORD
PRIMARY KEY (studentID) 
FOREIGN KEY  REFERENCES   
ALTER TABLE SECONDFORM

SELECT * FROM SECONDFORM 

SELECT ScoreID, Midtermexam, Finalexam, assignment1, assignment2
INTO SECONDFORM2
FROM GRADERECORD
PRIMARY KEY (ScoreID) 
FOREIGN KEY  REFERENCES  
--- ALTER TO ADD SCOREID ---
ALTER TABLE SECONDFORM2 
ADD ScoreID INT IDENTITY(1,1) 
CONSTRAINT PK_SCOREID PRIMARY KEY (SCOREID)

UPDATE SECONDFORM2 SET ScoreId IDENTITY

SELECT SCOREID, MIDTERMEXAM, FINALEXAM, GRADE FROM SECONDFORM2
SELECT * FROM SECONDFORM2 

CREATE TABLE Persons( 
Personid int identity (1,1) primary key, LastName varchar(255) NOT NULL FirstName varchar(255) 

SELECT * FROM SECONDFORM2 

ALTER TABLE SECONDFORM2 
DROP COLUMN SCOREIDD
